apiVersion: v1
kind: Service
metadata:
  namespace: logging
  labels:
    k8s.service: logstash
  name: logstash
spec:
  ports:
  - port: 5100
    targetPort: 5100
    protocol: TCP
    name: logstash
  selector:
    k8s.service: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
  labels:
    k8s.service: logstash
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      k8s.service: logstash
  template:
    metadata:
      labels:
        k8s.service: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.15.0
        imagePullPolicy: "Always"
        name: logstash
        ports:
        - containerPort: 5100
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 1024Mi
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
            name: logstash-config
      hostname: logstash
      restartPolicy: Always
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
